"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronRight, Clock3, ExternalLink, Laptop, LockKeyhole, MessageCircle, PackageCheck, Send, ShieldCheck, Sparkles, TriangleAlert, UserRound, X } from "lucide-react";
import { ASSIGNMENTS, HOME_META, MISSIONS, PEOPLE, TODAY } from "@/lib/data";
import { addDays, assignmentsFor, evaluateMove, formatDate, inclusiveEnd, matching, missionFor, nextRelease, openMissionHours } from "@/lib/domain";
import type { DemoState, Mission, Obligation, Person, ScenarioMove } from "@/lib/types";
import { Avatar, HomeBadge, Status } from "./ui";

export function PersonDetail({ person, state, onPlan, onEvidence, onAcknowledge, onReport }: { person: Person; state: DemoState; onPlan: (id: string) => void; onEvidence: (id: string, evidence: string) => void; onAcknowledge: (id: string) => void; onReport: (personId: string, text: string) => void }) {
  const [tab, setTab] = useState("overview");
  const [report, setReport] = useState("");
  const release = nextRelease(person.id);
  const landing = release && assignmentsFor(person.id).find(a=>a.start>=release.end && a.staffing==="committed");
  const obligations = state.obligations.filter(o=>o.personId===person.id);
  const notices = state.notices.filter(n=>n.personId===person.id);
  return <><div className="profile-summary"><Avatar person={person} large/><div><HomeBadge home={person.home}/><h3>{person.name}</h3><p>{person.grade} <span>·</span> {person.employment} <span>·</span> {person.weeklyHours}h/week</p></div></div><p className="profile-note">{person.note}</p><div className="detail-tabs" role="tablist" aria-label="Person details">{["overview","baggage","updates"].map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}{t==="baggage"&&<span>{obligations.filter(o=>o.state!=="satisfied").length}</span>}{t==="updates"&&<span>{notices.length}</span>}</button>)}</div>
  {tab==="overview"&&<div className="detail-section"><div className="detail-heading"><span className="eyebrow">THE NEXT CHAPTER</span><span className="text-muted">{person.owner} · Placement owner</span></div><div className="journey-cards"><div className="journey-card"><span className="journey-kicker">01 / CLOSING BOOKEND</span><h3>{release ? missionFor(release.missionId).client : "Available now"}</h3><p>{release ? missionFor(release.missionId).name : "No current commitment"}</p><strong>{release ? formatDate(inclusiveEnd(release.end),true) : "Today"}</strong><span>{release?.weeklyHours || person.weeklyHours} h/week released</span></div><span className="journey-arrow"><ArrowRight size={20}/></span><div className={`journey-card ${!landing?"journey-open":""}`}><span className="journey-kicker">02 / NEXT LANDING</span><h3>{landing?missionFor(landing.missionId).client:"An open possibility."}</h3><p>{landing?missionFor(landing.missionId).name:"No confirmed landing yet"}</p><strong>{landing?formatDate(landing.start,true):"Let’s find the right fit"}</strong><span>{landing?`${landing.weeklyHours} h/week · Accepted staffing`:"Next update: October 9"}</span></div></div>
  {landing&&<div className="status-row"><Status type="good">Authorized · Confirmed staffing</Status><Status type={landing.readiness==="blocked"?"blocked":"good"}>{landing.readiness==="blocked"?"Opening blocked":"Opening ready"}</Status></div>}
  <h4>What they bring</h4><div className="skill-tags">{person.skills.map(s=><span key={s}>{s}</span>)}</div><div className="owner-strip"><span className="owner-icon"><UserRound size={18}/></span><div><strong>{person.owner}</strong><span>Owns the next landing and keeps {person.name.split(" ")[0]} in the loop.</span></div></div><button className="button button-primary full-width" onClick={()=>onPlan(person.id)}><Sparkles size={16}/> Explore next landings <ArrowRight size={16}/></button><p className="fine-print">Monday–Friday calendar · America/New_York · No leave or internal reservations in this fixture.</p></div>}
  {tab==="baggage"&&<div className="detail-section"><h3>Travel light into the next mission.</h3><p className="text-muted">Every obligation has an owner. Start blockers stay separate from equipment returns and closeout.</p>{obligations.length?obligations.map(o=><ObligationCard key={o.id} obligation={o} onEvidence={onEvidence}/>):<div className="quiet-success"><PackageCheck size={30}/><h4>Nothing holding this chapter back.</h4><p>No recorded obligations for {person.name.split(" ")[0]}.</p></div>}</div>}
  {tab==="updates"&&<div className="detail-section"><h3>Keep the human in the loop.</h3>{notices.map(n=><div key={n.id} className="notice-card"><div><MessageCircle size={18}/><span>{formatDate(n.date)}</span><Status type={n.delivery==="bounced"?"blocked":"good"}>{n.delivery==="bounced"?"Bounced":"Demo inbox"}</Status></div><h4>{n.title}</h4><p>{n.body}</p><button className={`button ${n.acknowledged?"button-secondary":"button-primary"}`} onClick={()=>onAcknowledge(n.id)} disabled={n.acknowledged}>{n.acknowledged?<CheckCheck size={15}/>:<Check size={15}/>} {n.acknowledged?"Acknowledged":"Acknowledge update"}</button></div>)}{!notices.length&&<p className="text-muted">No published updates in this demo for {person.name.split(" ")[0]}.</p>}<p className="fine-print">Acknowledgment confirms receipt, not acceptance of an assignment. Demo actions stay in this browser.</p><form className="report-form" onSubmit={e=>{e.preventDefault();if(report.trim()){onReport(person.id,report.trim());setReport("");}}}><label htmlFor="report">A question or something in the way?</label><textarea id="report" placeholder="Tell your placement owner what you need…" value={report} onChange={e=>setReport(e.target.value)} required maxLength={1000}/><button className="button button-secondary" type="submit"><Send size={14}/> Record demo question</button></form>{state.reported.filter(r=>r.personId===person.id).map(r=><div key={r.id} className="recorded-question"><MessageCircle size={14}/><p>{r.text}</p><span>Recorded locally</span></div>)}</div>}
  </>;
}

export function ObligationCard({ obligation:o, onEvidence }: { obligation: Obligation; onEvidence: (id: string, evidence: string) => void }) {
  const [expanded,setExpanded]=useState(false);
  const [evidence,setEvidence]=useState("");
  const Icon=o.category==="equipment"?Laptop:o.category==="access"?LockKeyhole:PackageCheck;
  return <div className="obligation-card"><div className="obligation-top"><span className={`obligation-icon ${o.blocksStart?"is-blocker":""}`}><Icon size={19}/></span><div><h4>{o.title}</h4><span>{o.owner} · Due {formatDate(o.due)}</span></div><Status type={o.state==="satisfied"?"good":o.blocksStart?"blocked":"muted"}>{o.state==="submitted"?"Awaiting verification":o.state==="satisfied"?"Completed":o.blocksStart?"Start blocker":"Closeout"}</Status></div><p>{o.detail}</p>{o.evidence&&<p className="evidence-text"><ShieldCheck size={14}/>{o.evidence}</p>}{o.state==="open"&&!expanded&&<button className="text-button" onClick={()=>setExpanded(true)}>Submit completion evidence <ArrowUpRight size={14}/></button>}{expanded&&o.state==="open"&&<form onSubmit={e=>{e.preventDefault();if(evidence.trim())onEvidence(o.id,evidence.trim());}}><label htmlFor={`evidence-${o.id}`}>What was completed? Add a verification reference.</label><textarea id={`evidence-${o.id}`} required minLength={8} maxLength={500} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="e.g. Return arranged; tracking reference DEMO-1042"/><button className="button button-primary" type="submit"><Check size={14}/> Submit for verification</button></form>}{o.state==="submitted"&&<span className="fine-print">Submitted to {o.owner}. The obligation stays unresolved until independently verified.</span>}</div>;
}

export function Planner({ initialPersonId, initialMissionId, state, onSave }: { initialPersonId?: string; initialMissionId?: string; state: DemoState; onSave: (move: ScenarioMove) => void }) {
  const [personId,setPersonId]=useState(initialPersonId||"p1");
  const initialMission=missionFor(initialMissionId||"m2");
  const [missionId,setMissionId]=useState(initialMission.id);
  const [start,setStart]=useState(initialMission.start<TODAY?TODAY:initialMission.start);
  const [end,setEnd]=useState(inclusiveEnd(initialMission.end));
  const [hours,setHours]=useState(PEOPLE.find(p=>p.id===(initialPersonId||"p1"))!.weeklyHours);
  const person=PEOPLE.find(p=>p.id===personId)!;
  const mission=missionFor(missionId);
  const fit=matching(person,mission,state.obligations);
  const move:ScenarioMove={id:"preview",personId,missionId,start,end:end?addDays(end,1):"",weeklyHours:hours};
  const issues=evaluateMove(move,person,mission,state.moves);
  const changeMission=(id:string)=>{const m=missionFor(id);setMissionId(id);setStart(m.start<TODAY?TODAY:m.start);setEnd(inclusiveEnd(m.end));};
  return <form className="planner" onSubmit={e=>{e.preventDefault();if(!issues.length)onSave({...move,id:crypto.randomUUID()});}}><div className="planner-intro"><span className="planner-spark"><Sparkles size={24}/></span><div><h3>Good fit. Great next chapter.</h3><p>Explore a landing, see the impact, then save it to your scenario.</p></div></div><div className="form-grid"><label>Who’s making the move?<select value={personId} onChange={e=>{setPersonId(e.target.value);setHours(PEOPLE.find(p=>p.id===e.target.value)!.weeklyHours);}}>{PEOPLE.map(p=><option key={p.id} value={p.id}>{p.name} · {p.home}</option>)}</select></label><label>Where could they land?<select value={missionId} onChange={e=>changeMission(e.target.value)}>{MISSIONS.filter(m=>m.end>TODAY).map(m=><option key={m.id} value={m.id}>{m.client} · {m.name}</option>)}</select></label><label>First working date<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Last working date<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Hours per week<input type="number" min={0.25} max={person.weeklyHours} step={0.25} required value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><div className="form-summary"><span>PERSON’S CAPACITY</span><strong>{person.weeklyHours}<small> h / week</small></strong></div></div><div className="fit-panel"><div className="fit-panel-heading"><span><span className="home-dot" style={{background:HOME_META[mission.home].color}}/>{fit.label}</span><Status type={mission.commercial==="authorized"?"good":"warning"}>{mission.commercial}</Status></div><div className="skill-tags">{mission.skills.map(s=><span key={s} className={person.skills.includes(s)?"skill-match":"skill-missing"}>{person.skills.includes(s)?<Check size={12}/>:<TriangleAlert size={12}/>} {s}</span>)}</div>{fit.missing.length>0&&<p>Verify required skills: {fit.missing.join(", ")}. This is a proposal, not a ready placement.</p>}{fit.blockers.length>0&&<p>{fit.blockers.length} start prerequisite(s) remain: {fit.blockers.map(o=>o.title).join("; ")}.</p>}<p>Approval owner: {mission.owner}. {person.home!==mission.home?`Cross-HOME review also needed from ${person.owner}.`:"Same-HOME placement."}</p></div>{issues.length>0?<div className="validation-errors" role="alert"><TriangleAlert size={17}/><div><strong>This move needs an adjustment.</strong>{issues.map(issue=><p key={issue}>{issue}</p>)}</div></div>:<div className="validation-success"><ShieldCheck size={17}/><span>Hours and dates fit the current demo plan. Readiness and approvals remain separate.</span></div>}<div className="planner-footer"><span><LockKeyhole size={13}/> No staffing changes or notices sent</span><button type="submit" className="button button-primary" disabled={!!issues.length}>Save to scenario <ArrowRight size={16}/></button></div></form>;
}

export function MissionDetail({ mission, onPerson, onPlan }: { mission: Mission; onPerson: (id: string) => void; onPlan: () => void }) {
  const assignments=ASSIGNMENTS.filter(a=>a.missionId===mission.id);
  return <div className="detail-section mission-detail"><HomeBadge home={mission.home}/><div className="mission-detail-logo" style={{color:HOME_META[mission.home].color}}>{mission.initials}</div><h3>{mission.client}</h3><p className="mission-description">{mission.description}</p><div className="status-row"><Status type={mission.commercial==="authorized"?"good":"warning"}>{mission.commercial==="authorized"?"Commercially authorized":"Contingent commercial demand"}</Status><span className="text-muted">{mission.owner} · Delivery owner</span></div><div className="mission-facts"><div><span>MISSION DATES</span><strong>{formatDate(mission.start)} — {formatDate(inclusiveEnd(mission.end))}</strong></div><div><span>FUNDED DEMAND</span><strong>{mission.commercial==="authorized"?mission.weeklyHours:"—"}<small> h/week</small></strong></div><div><span>OPEN CAPACITY</span><strong>{openMissionHours(mission)}<small> h/week peak</small></strong></div><div><span>SOW BASIS</span><strong>Dated seats</strong></div></div><h4>The capabilities that matter</h4><div className="skill-tags">{mission.skills.map(s=><span key={s}>{s}</span>)}</div><h4>The people behind the mission</h4>{assignments.map(a=>{const p=PEOPLE.find(p=>p.id===a.personId)!;return <button className="mission-person" key={a.id} onClick={()=>onPerson(p.id)}><Avatar person={p}/><span><strong>{p.name}</strong><small>{a.weeklyHours}h/week · {formatDate(a.start)}—{formatDate(inclusiveEnd(a.end))}</small></span><Status type={a.staffing==="committed"?"good":"muted"}>{a.staffing==="committed"?"Confirmed":"Proposed"}</Status><ChevronRight size={15}/></button>;})}{!assignments.length&&<p className="text-muted">This mission is ready for its first proposed team.</p>}<button className="button button-primary full-width" onClick={onPlan}>Preview a placement <ArrowUpRight size={16}/></button><p className="fine-print">Synthetic SOW revision 1 · Dates use an inclusive last day in this view. Actual release, client access, and closeout are separate obligations.</p></div>;
}

export function ScenarioDetail({ state, onName, onRemove, onPlan, onRequest, onReset }: {state:DemoState;onName:(name:string)=>void;onRemove:(id:string)=>void;onPlan:()=>void;onRequest:()=>void;onReset:()=>void}) {
  return <div className="detail-section"><div className="scenario-intro"><Sparkles size={28}/><h3>Room to think. Space to try.</h3><p>Your scenario is a set of proposed moves over the approved plan.</p></div><label className="field-label">Scenario name<input maxLength={60} value={state.scenarioName} onChange={e=>onName(e.target.value)}/></label><div className="status-row"><Status type="warning">{state.scenarioStatus==="draft"?"Draft scenario":"Demo approval requested"}</Status><span className="text-muted">Baseline: October 5, 2026</span></div>{state.moves.map(m=>{const p=PEOPLE.find(p=>p.id===m.personId)!;const mission=missionFor(m.missionId);return <div className="scenario-move" key={m.id}><Avatar person={p}/><div><strong>{p.name} <ArrowRight size={13}/> {mission.client}</strong><span>{formatDate(m.start)}—{formatDate(inclusiveEnd(m.end))} · {m.weeklyHours}h/week</span></div><button className="icon-button" aria-label={`Remove ${p.name}'s proposed move`} onClick={()=>onRemove(m.id)}><X size={16}/></button></div>;})}{!state.moves.length&&<p className="scenario-empty">A blank page for the team’s next chapter. Add your first move to start comparing possibilities.</p>}<button className="button button-secondary full-width" onClick={onPlan}>Add a proposed move <ArrowUpRight size={16}/></button>{state.moves.length>0&&<><div className="scenario-impact"><span>{state.moves.length}<small>proposed moves</small></span><span>{state.moves.reduce((sum,m)=>sum+m.weeklyHours,0)}<small>h/week proposed</small></span><span>0<small>notices sent</small></span></div><button className="button button-primary full-width" disabled={state.scenarioStatus==="pending_approval"} onClick={onRequest}>{state.scenarioStatus==="pending_approval"?<CheckCheck size={16}/>:<Send size={16}/>} {state.scenarioStatus==="pending_approval"?"Queued in demo Decisions":"Request review in demo"}</button></>}<p className="fine-print">Synthetic workspace only. An authenticated server must revalidate capacity, commercial authority, readiness, and revisions before any real approve-and-publish action.</p><button className="text-button muted" onClick={onReset}>Return to approved plan <ExternalLink size={13}/></button></div>;
}
