"use client";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { ArrowRight, ArrowUpRight, Bell, BookOpen, Check, ChevronDown, Command, Compass, Flag, HelpCircle, Layers3, LayoutGrid, Menu, MessageCircle, Moon, Play, Plus, Search, Settings2, ShieldCheck, Sparkles, Sun, Target, TriangleAlert, Users, X } from "lucide-react";
import { ASSIGNMENTS, HOMES, HOME_META, INITIAL_STATE, MISSIONS, PEOPLE, TODAY } from "@/lib/data";
import { addDays, coverageFor, formatDate, inclusiveEnd, nextRelease, openMissionHours, uncoveredHours } from "@/lib/domain";
import type { DemoState, Focus, Home, ScenarioMove, View } from "@/lib/types";
import { Avatar, EmptyState, Modal, OrbitVisual, Status } from "./ui";
import { Runway } from "./runway";
import { MissionDetail, PersonDetail, ScenarioDetail } from "./details";
import { clearPlannerDrafts, Planner } from "./planner";
import { DecisionRail, DecisionsView, getDecisions, MissionsView, MyBookendsView, Presentation } from "./views";

type PlannerOrigin = {type:"person";id:string;tab?:"overview"|"baggage"}|{type:"mission";id:string}|{type:"scenario"};
type Dialog = PlannerOrigin|{type:"planner";id?:string;missionId?:string;moveId?:string;origin?:PlannerOrigin}|{type:"search"}|{type:"notifications"}|{type:"help"}|{type:"settings"}|{type:"presentation"};
const NAV=[{id:"runway" as View,label:"Runway",Icon:Compass},{id:"missions" as View,label:"Missions",Icon:Layers3},{id:"decisions" as View,label:"Decisions",Icon:Flag},{id:"my-bookends" as View,label:"My Bookends",Icon:BookOpen}];
const STORAGE_KEY="bookends.synthetic-workspace.v1";

function readDemoState():DemoState|null {
  try { const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return null;const s=JSON.parse(raw) as DemoState;
    if(s.version!==1||!Array.isArray(s.moves)||!Array.isArray(s.notices)||!Array.isArray(s.obligations)||!Array.isArray(s.activity)||!Array.isArray(s.reported)||typeof s.scenarioName!=="string"||!["draft","pending_approval"].includes(s.scenarioStatus))return null;
    if(s.moves.some(m=>!PEOPLE.some(p=>p.id===m.personId)||!MISSIONS.some(p=>p.id===m.missionId)||typeof m.weeklyHours!=="number"||typeof m.start!=="string"||typeof m.end!=="string"))return null;
    if(s.obligations.length!==INITIAL_STATE.obligations.length||s.notices.length!==INITIAL_STATE.notices.length)return null;
    // Only restore interactive fields on known synthetic records.
    return {...INITIAL_STATE,moves:s.moves.slice(0,100),scenarioName:s.scenarioName.slice(0,60),scenarioStatus:s.scenarioStatus,obligations:INITIAL_STATE.obligations.map(o=>{const saved=s.obligations.find(x=>x.id===o.id);return saved&&saved.state==="submitted"?{...o,state:"submitted",evidence:String(saved.evidence||"").slice(0,500)}:o;}),notices:INITIAL_STATE.notices.map(n=>({...n,acknowledged:!!s.notices.find(x=>x.id===n.id)?.acknowledged})),activity:s.activity.slice(0,20),reported:s.reported.filter(r=>PEOPLE.some(p=>p.id===r.personId)&&typeof r.text==="string").slice(0,100)};
  }catch{return null;}
}

export function Workspace() {
  const [view,setView]=useState<View>("runway");
  const [home,setHome]=useState<Home|"all">("all");
  const [query,setQuery]=useState("");
  const [weeks,setWeeks]=useState(13);
  const [focus,setFocus]=useState<Focus>("all");
  const [missionOpenOnly,setMissionOpenOnly]=useState(false);
  const [state,setState]=useState<DemoState>(INITIAL_STATE);
  const [ready,setReady]=useState(false);
  const [scenario,setScenario]=useState(false);
  const [dialog,setDialog]=useState<Dialog|null>(null);
  const [toast,setToast]=useState("");
  const [theme,setTheme]=useState("light");
  const [mobileNav,setMobileNav]=useState(false);
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{const saved=readDemoState();if(saved)setState(saved);const params=new URLSearchParams(window.location.search);const v=params.get("view");if(NAV.some(n=>n.id===v))setView(v as View);const p=params.get("person");if(p&&PEOPLE.some(x=>x.id===p))setDialog({type:"person",id:p});setTheme("light");setReady(true);},[]);
  useEffect(()=>{if(ready){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{/* Private mode can disable storage; the demo remains usable for this visit. */}}},[state,ready]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==="k"){e.preventDefault();setDialog({type:"search"});}};window.addEventListener("keydown",handler);return()=>{window.removeEventListener("keydown",handler);if(timer.current)clearTimeout(timer.current);};},[]);
  const notify=(message:string)=>{setToast(message);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(""),4800);};
  const showPeople=(selected:Focus)=>{setFocus(selected);requestAnimationFrame(()=>{document.getElementById("runway-title")?.focus({preventScroll:true});document.getElementById("runway-results")?.scrollIntoView({block:"start",behavior:"instant"});});};
  const navigate=(v:View)=>{setView(v);setMobileNav(false);setDialog(null);window.history.replaceState(null,"",`?view=${v}`);window.scrollTo({top:0,behavior:"instant"});};
  const openPerson=(id:string,tab:"overview"|"baggage"="overview")=>{setDialog({type:"person",id,tab});window.history.replaceState(null,"",`?view=${view}&person=${id}`);};
  const closeDialog=()=>{setDialog(null);window.history.replaceState(null,"",`?view=${view}`);};
  const openPlanner=(options:{id?:string;missionId?:string;moveId?:string}={})=>{
    setDialog(current=>({type:"planner",...options,origin:current&&(current.type==="person"||current.type==="mission"||current.type==="scenario")?current:undefined}));
    window.history.replaceState(null,"",`?view=${view}`);
  };
  const plan=(id?:string)=>openPlanner({id});
  const backFromPlanner=()=>{
    if(dialog?.type!=="planner"||!dialog.origin)return;
    const origin=dialog.origin;
    setDialog(origin);
    window.history.replaceState(null,"",`?view=${view}${origin.type==="person"?`&person=${origin.id}`:""}`);
  };
  const addActivity=(s:DemoState,title:string,detail:string):DemoState=>({...s,activity:[{id:crypto.randomUUID(),title,detail,time:"Just now"},...s.activity].slice(0,20)});
  const saveMove=(move:ScenarioMove)=>{setState(s=>addActivity({...s,moves:s.moves.some(m=>m.id===move.id)?s.moves.map(m=>m.id===move.id?move:m):[...s.moves,move],scenarioStatus:"draft"},"A new possibility on the runway",`${PEOPLE.find(p=>p.id===move.personId)!.name} · ${move.weeklyHours}h/week proposed`));setScenario(true);setDialog({type:"scenario"});setView("runway");window.history.replaceState(null,"","?view=runway");notify("Move saved. You can edit it below or add the next person.");};
  const evidence=(id:string,text:string)=>{setState(s=>addActivity({...s,obligations:s.obligations.map(o=>o.id===id?{...o,state:"submitted",evidence:text}:o)},"One step closer to a clean handoff","Evidence submitted · awaiting owner verification"));notify("Evidence saved in this demo. The owner still needs to verify it.");};
  const acknowledge=(id:string)=>{setState(s=>addActivity({...s,notices:s.notices.map(n=>n.id===id?{...n,acknowledged:true}:n)},"The team is in the loop","Update acknowledged · staffing acceptance unchanged"));notify("Update acknowledged in this demo. You’re in the loop.");};
  const report=(personId:string,text:string)=>{setState(s=>({...s,reported:[...s.reported,{id:crypto.randomUUID(),personId,text}]}));notify("Question recorded in demo Decisions. No external message was sent.");};
  const end=addDays(TODAY,weeks*7);
  const basePeople=PEOPLE.filter(p=>(home==="all"||p.home===home)&&(p.name+" "+p.skills.join(" ")).toLowerCase().includes(query.toLowerCase()));
  const closing=basePeople.filter(p=>{const r=nextRelease(p.id);return r&&r.end<=end;});
  const exposed=basePeople.filter(p=>p.employment==="W2"&&uncoveredHours(p,TODAY,end)>0);
  const blockers=basePeople.filter(p=>state.obligations.some(o=>o.personId===p.id&&o.blocksStart&&o.state!=="satisfied"&&o.due<end));
  const openMissions=MISSIONS.filter(m=>m.commercial==="authorized"&&(home==="all"||m.home===home)&&openMissionHours(m,TODAY,end)>0);
  const people=focus==="closing"?closing:focus==="uncovered"?exposed:focus==="blocked"?blockers:basePeople;
  const coverage=coverageFor(basePeople,TODAY,end);
  const decisions=getDecisions(state);
  const pendingNotices=state.notices.filter(n=>!n.acknowledged).length;
  const series=(kind: "closing"|"uncovered"|"open"|"blocked")=>Array.from({length:7},(_,i)=>{
    const start=addDays(TODAY,Math.floor(i*(weeks-1)/6)*7), finish=addDays(start,7);
    if(kind==="closing")return basePeople.filter(p=>{const r=nextRelease(p.id);return r&&r.end>start&&r.end<=finish;}).length;
    if(kind==="uncovered")return basePeople.filter(p=>p.employment==="W2").reduce((sum,p)=>sum+uncoveredHours(p,start,finish),0);
    if(kind==="open")return MISSIONS.filter(m=>m.commercial==="authorized"&&(home==="all"||m.home===home)&&openMissionHours(m,start,finish)>0).length;
    return basePeople.filter(p=>state.obligations.some(o=>o.personId===p.id&&o.blocksStart&&o.state!=="satisfied"&&o.due>=start&&o.due<finish)).length;
  });
  const sparkY=(values:number[],value:number)=>38-(Math.max(...values)?value/Math.max(...values)*30:0);
  const stats=[{id:"closing" as Focus,label:"Closing bookends",value:closing.length,unit:`of ${basePeople.length} people`,detail:`In the next ${weeks} weeks`,Icon:Flag,color:"lime",spark:series("closing")},{id:"uncovered" as Focus,label:"People needing a landing",value:exposed.length,unit:"W2 people",detail:"Uncovered hours in horizon",Icon:Users,color:"blue",spark:series("uncovered")},{id:"open-seats" as Focus,label:"Missions with open demand",value:openMissions.length,unit:"funded missions",detail:"Good work. Room for great people.",Icon:Target,color:"purple",spark:series("open")},{id:"blocked" as Focus,label:"Start blockers",value:blockers.length,unit:"people affected",detail:"A little help to get moving",Icon:TriangleAlert,color:"orange",spark:series("blocked")}];
  const currentNav=NAV.find(n=>n.id===view)!;
  return <div className={`workspace theme-${theme}`}>
    <a className="skip-link" href="#main-content">Skip to workspace</a>
    <aside className={`sidebar ${mobileNav?"sidebar-open":""}`}><button className="logo-button" aria-label="BOOKENDS home" onClick={()=>navigate("runway")}><span className="brand-mark">[<i/>]</span></button><div className="sidebar-divider"/><nav aria-label="Main navigation">{NAV.map(({id,label,Icon})=><button key={id} onClick={()=>navigate(id)} className={`nav-item ${view===id?"active":""}`} aria-current={view===id?"page":undefined}><span className="nav-icon"><Icon size={21} strokeWidth={1.6}/>{id==="decisions"&&<i/>}</span><span>{label}</span></button>)}<a href="/admin?section=engagements" className="nav-item" aria-label="Engagements"><span className="nav-icon"><Users size={21} strokeWidth={1.6}/></span><span>Engagements</span></a><a href="/admin" className="nav-item" aria-label="Administration"><span className="nav-icon"><ShieldCheck size={21} strokeWidth={1.6}/></span><span>Admin</span></a></nav><div className="sidebar-bottom"><button className="sidebar-utility" aria-label="Workspace guide" onClick={()=>setDialog({type:"help"})}><HelpCircle size={20}/></button><button className="sidebar-utility" aria-label="Appearance and demo settings" onClick={()=>setDialog({type:"settings"})}><Settings2 size={20}/></button><span className="sidebar-bottom-line"/><button className="profile-button" aria-label="My Bookends" onClick={()=>navigate("my-bookends")}>JL<span/></button></div></aside>
    {mobileNav&&<button className="mobile-nav-backdrop" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}
    <div className="workspace-main"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle navigation"><Menu size={21}/></button><button className="wordmark" onClick={()=>navigate("runway")}>BOOKENDS<span>®</span></button><span className="topbar-slash">/</span><span className="workspace-label">Workspace <ChevronDown size={12}/></span><span className="demo-pill"><span/>DEMO</span></div><div className="topbar-actions"><button className="command-button" onClick={()=>setDialog({type:"search"})}><Search size={15}/><span>Jump to anything</span><kbd>Ctrl K</kbd></button><span className="topbar-divider"/><button className="icon-button theme-toggle" aria-label={theme==="dark"?"Switch to light theme":"Switch to dark theme"} onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button notification-button" aria-label={`Notifications, ${pendingNotices} awaiting acknowledgment`} onClick={()=>setDialog({type:"notifications"})}><Bell size={18}/>{pendingNotices>0&&<i/>}</button><button className="topbar-avatar" aria-label="Open My Bookends" onClick={()=>navigate("my-bookends")}>JL</button></div></header>
    <main id="main-content" className="main-content"><div className="context-row"><span><span className="context-dot"/> MISSION CONTROL <ChevronRightMini/> {currentNav.label}</span><div><span className="as-of">SYNTHETIC DATA · OCT 5, 2026</span><button className="present-button" onClick={()=>setDialog({type:"presentation"})}><Play size={12} fill="currentColor"/> Present <ArrowUpRight size={13}/></button></div></div>
    {view==="runway"&&<><section className="hero"><div className="hero-copy"><div className="hero-eyebrow"><span className="live-dot"/> YOUR PEOPLE. THEIR NEXT POSSIBILITY.</div><h1>Great people.<br/><span>Extraordinary trajectories.</span></h1><p>See the ending. Find the landing. Make the next chapter count.</p><div className="hero-actions"><button className="button button-primary" onClick={()=>plan()}><Plus size={17}/> Plan the next move <ArrowUpRight size={17}/></button><button className="hero-secondary" onClick={()=>{setScenario(true);setDialog({type:"scenario"});}}><Layers3 size={15}/>Explore a scenario <ArrowRight size={14}/></button></div></div><OrbitVisual percent={coverage.percent}/><div className="hero-coordinate">40° 00′ N <span>THE FUTURE IS A TEAM SPORT.</span></div></section>
    <div className="stats-grid">{stats.map(({id,label,value,unit,detail,Icon,color,spark})=><button key={id} className={`stat-card stat-${color} ${focus===id?"stat-active":""}`} onClick={()=>{if(id==="open-seats"){setMissionOpenOnly(true);navigate("missions");}else showPeople(focus===id?"all":id);}} aria-controls={id!=="open-seats"?"runway-results":undefined} aria-pressed={id!=="open-seats"?focus===id:undefined}><div className="stat-heading"><span>{label}</span><Icon size={16}/></div><div className="stat-middle"><strong>{String(value).padStart(2,"0")}</strong><span>{unit}</span><svg width="83" height="38" viewBox="0 0 83 45" aria-hidden="true"><title>{`Seven weekly samples across the horizon: ${spark.join(", ")}. Uncovered capacity is in hours; other series count records.`}</title><path d={`M${spark.map((v,i)=>`${i*12+3},${sparkY(spark,v)}`).join(" L")}`} fill="none" stroke="currentColor" strokeWidth="1.4"/><circle cx={75} cy={sparkY(spark,spark[6])} r="2.5" fill="currentColor"/></svg></div><div className="stat-detail">{detail}<ArrowUpRight size={13}/></div></button>)}</div>
    <div className="runway-layout"><Runway people={people} home={home} setHome={setHome} query={query} setQuery={setQuery} weeks={weeks} setWeeks={setWeeks} focus={focus} setFocus={showPeople} onPerson={openPerson} onReviewBlockers={id=>openPerson(id,"baggage")} onPlan={plan} obligations={state.obligations} moves={state.moves} scenario={scenario} onScenario={()=>setDialog({type:"scenario"})} scenarioName={state.scenarioName} /><DecisionRail state={state} onPerson={openPerson} onView={()=>navigate("decisions")} onPlan={plan}/></div><section className="activity-strip"><span className="activity-label"><span className="live-dot"/> THE MOMENTUM</span>{state.activity.slice(0,3).map(event=><div className="activity-item" key={event.id}><span className="activity-check"><Check size={12}/></span><div><strong>{event.title}</strong><span>{event.detail}</span></div><time>{event.time}</time></div>)}</section><div className="horizon-note"><ShieldCheck size={13}/><span>Planning continues beyond the visible horizon. {basePeople.filter(p=>{const r=nextRelease(p.id);return r&&r.end>end;}).length} next releases fall after {formatDate(inclusiveEnd(end))}. Uncovered hours remain visible in each person’s plan.</span></div></>}
    {view==="missions"&&<MissionsView key={String(missionOpenOnly)} initialOpenOnly={missionOpenOnly} weeks={weeks} home={home} onHome={setHome} onMission={id=>setDialog({type:"mission",id})}/>}
    {view==="decisions"&&<DecisionsView state={state} onPerson={openPerson} onPlan={plan} onScenario={()=>setDialog({type:"scenario"})}/>}
    {view==="my-bookends"&&<MyBookendsView state={state} onAcknowledge={acknowledge} onEvidence={evidence} onPerson={openPerson} onPlan={plan}/>}
    <footer className="workspace-footer"><span>BOOKENDS <span>·</span> EVERY ENDING. A NEW BEGINNING.</span><span>Explore freely. This workspace uses fictional people and local demo data.</span><button onClick={()=>setDialog({type:"help"})}>Made for the way people move <ArrowUpRight size={12}/></button></footer></main></div>
    {dialog?.type==="person"&&<Modal title="A person. A whole world of possibility." eyebrow="PEOPLE / NEXT CHAPTER" onClose={closeDialog} wide><PersonDetail key={`${dialog.id}:${dialog.tab||"overview"}`} initialTab={dialog.tab} person={PEOPLE.find(p=>p.id===dialog.id)!} state={state} onPlan={plan} onEvidence={evidence} onAcknowledge={acknowledge} onReport={report}/></Modal>}
    {dialog?.type==="mission"&&<Modal title={MISSIONS.find(m=>m.id===dialog.id)!.name} eyebrow="MISSION BRIEFING" onClose={closeDialog} wide><MissionDetail mission={MISSIONS.find(m=>m.id===dialog.id)!} onPerson={openPerson} onPlan={()=>openPlanner({missionId:dialog.id})}/></Modal>}
    {dialog?.type==="planner"&&<Modal title={dialog.moveId?"Fine-tune this move":"Plan the next move"} eyebrow="SCENARIO STUDIO" className="modal-planner" onClose={closeDialog} onBack={dialog.origin?backFromPlanner:undefined} wide><Planner key={dialog.moveId||dialog.id||dialog.missionId||"default"} initialPersonId={dialog.id} initialMissionId={dialog.missionId} editingMove={state.moves.find(m=>m.id===dialog.moveId)} state={state} onSave={saveMove}/></Modal>}
    {dialog?.type==="scenario"&&<Modal title="Your next chapter" eyebrow="SCENARIO STUDIO" onClose={closeDialog}><ScenarioDetail state={state} onName={name=>setState(s=>({...s,scenarioName:name}))} onRemove={id=>{clearPlannerDrafts(id);setState(s=>({...s,moves:s.moves.filter(m=>m.id!==id),scenarioStatus:"draft"}));}} onEdit={moveId=>openPlanner({moveId})} onPlan={()=>plan()} onRequest={()=>{setState(s=>({...s,scenarioStatus:"pending_approval"}));notify("Review request added to demo Decisions. No external notifications sent.");}} onReset={()=>{setScenario(false);closeDialog();}}/></Modal>}
    {dialog?.type==="search"&&<Modal title="Where do you want to go?" eyebrow="COMMAND CENTER" onClose={closeDialog}><CommandSearch onPerson={openPerson} onMission={id=>setDialog({type:"mission",id})} onNavigate={navigate}/></Modal>}
    {dialog?.type==="notifications"&&<Modal title="Stay in the loop." eyebrow="YOUR DEMO INBOX" onClose={closeDialog}><div className="detail-section">{state.notices.map(n=><button className="inbox-item" key={n.id} onClick={()=>openPerson(n.personId)}><Avatar person={PEOPLE.find(p=>p.id===n.personId)!}/><div><strong>{n.title}</strong><span>{PEOPLE.find(p=>p.id===n.personId)!.name} · {formatDate(n.date)}</span><Status type={n.acknowledged?"good":n.delivery==="bounced"?"blocked":"warning"}>{n.acknowledged?"Acknowledged":n.delivery==="bounced"?"Bounced · needs recovery":"Awaiting acknowledgment"}</Status></div><ArrowUpRight size={16}/></button>)}</div></Modal>}
    {dialog?.type==="help"&&<Modal title="Every ending deserves a beginning." eyebrow="WELCOME TO BOOKENDS" onClose={closeDialog}><div className="detail-section help-content"><p>BOOKENDS connects people, missions, and the transitions between them. Try the full visual journey with fictional data.</p>{[{n:"01",title:"See the ending",text:"Follow mission ribbons on the Runway. Select a person to open their next chapter."},{n:"02",title:"Find the landing",text:"Preview a placement. Dates and hours are checked against existing commitments before it becomes a draft."},{n:"03",title:"Clear the baggage",text:"Review access, equipment, and handoff tasks. Submit evidence while keeping verification separate."},{n:"04",title:"Keep people in the loop",text:"Explore My Bookends, acknowledge an update, and take the plan into a six-scene executive presentation."}].map(step=><div className="help-step" key={step.n}><span>{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}<div className="demo-notice"><ShieldCheck size={20}/><p>This is an interactive product demo. Edits are saved only in this browser. Production identity, Neon persistence, approvals, email delivery, and secure executive sharing are not connected.</p></div></div></Modal>}
    {dialog?.type==="settings"&&<Modal title="Make it your space." eyebrow="APPEARANCE & DEMO" onClose={closeDialog}><div className="detail-section"><h3>Your workspace, your way.</h3><p className="text-muted">Manage clients, HOMEs, people, missions, playbooks, and account access.</p><a className="button button-secondary" href="/admin">Open Administration <ArrowUpRight size={15}/></a><h3>A view for every room.</h3><div className="theme-options">{["dark","light","projector"].map(t=><button key={t} className={`${theme===t?"selected":""} theme-option-${t}`} onClick={()=>setTheme(t)}><span><i/><i/><i/></span><strong>{t}</strong>{theme===t&&<Check size={14}/>}</button>)}</div><h3>A fresh beginning.</h3><p className="text-muted">Reset only this browser’s synthetic scenario, unfinished moves, evidence, and acknowledgments.</p><button className="button button-secondary" onClick={()=>{clearPlannerDrafts();setState(INITIAL_STATE);setScenario(false);notify("Demo reset. A fresh runway is ready.");closeDialog();}}>Reset demo workspace <ArrowRight size={15}/></button><p className="fine-print">No real staff or client records are stored here.</p></div></Modal>}
    {dialog?.type==="presentation"&&<Modal title="Executive presentation" onClose={closeDialog} fullscreen><Presentation state={state} people={basePeople} weeks={weeks} onClose={closeDialog}/></Modal>}
    <div className={`toast ${toast?"toast-visible":""}`} role="status" aria-live="polite">{toast&&<><span><Check size={17}/></span><p>{toast}</p><button aria-label="Dismiss notification" onClick={()=>setToast("")}><X size={15}/></button></>}</div>
  </div>;
}

function ChevronRightMini(){return <span className="breadcrumb-separator">/</span>;}
function CommandSearch({onPerson,onMission,onNavigate}:{onPerson:(id:string)=>void;onMission:(id:string)=>void;onNavigate:(view:View)=>void}) {
  const [query,setQuery]=useState("");
  const showAdmin=!query||/admin|client|config|setting|setup/i.test(query);
  const people=PEOPLE.filter(p=>(p.name+" "+p.home+" "+p.skills.join(" ")).toLowerCase().includes(query.toLowerCase()));
  const missions=MISSIONS.filter(m=>(m.name+" "+m.client).toLowerCase().includes(query.toLowerCase()));
  return <div className="command-search"><label className="command-input"><Search size={20}/><input autoFocus placeholder="People, missions, possibilities…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search everything"/></label>{!query&&<div className="command-nav">{NAV.map(n=><button key={n.id} onClick={()=>onNavigate(n.id)}><n.Icon size={17}/>{n.label}<ArrowUpRight size={15}/></button>)}</div>}{showAdmin&&<div className="command-nav"><a href="/admin"><ShieldCheck size={17}/>Administration<ArrowUpRight size={15}/></a></div>}<div className="command-results"><span className="eyebrow">PEOPLE</span>{people.slice(0,5).map(p=><button key={p.id} onClick={()=>onPerson(p.id)}><Avatar person={p}/><div><strong>{p.name}</strong><span>{p.home} · {p.grade}</span></div><ArrowUpRight size={16}/></button>)}<span className="eyebrow">MISSIONS</span>{missions.slice(0,4).map(m=><button key={m.id} onClick={()=>onMission(m.id)}><span className="search-mission-icon" style={{color:HOME_META[m.home].color}}>{m.initials}</span><div><strong>{m.client}</strong><span>{m.name}</span></div><ArrowUpRight size={16}/></button>)}{!people.length&&!missions.length&&!showAdmin&&<EmptyState title="No matches yet." detail="Try a person, skill, HOME, or client name."/>}</div></div>;
}
