import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";
import type { Journey, JourneyActor, JourneyKind, JourneyRole, JourneyTemplate, BaggageObligation, ObligationStatus } from "../lib/journeys/types";

const audit = () => ({ createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
const revision = () => integer("revision").notNull().default(1);
// Reviewed SQL migrations are authoritative for FORCE RLS, grants, immutable triggers, and DEFERRABLE constraints.
export const organizations = pgTable("be_organizations", { id: uuid("id").primaryKey(), name: text("name").notNull(), revision: revision(), ...audit() });
export const clients = pgTable("be_clients", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), code: text("code").notNull(), name: text("name").notNull(),
  contactName: text("contact_name"), contactEmail: text("contact_email"), notes: text("notes").notNull().default(""), active: boolean("active").notNull().default(true), revision: revision(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), unique().on(table.organizationId, table.code)]);
export const homes = pgTable("be_homes", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), code: text("code").notNull(), name: text("name").notNull(), description: text("description").notNull().default(""), active: boolean("active").notNull().default(true), revision: revision(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), unique().on(table.organizationId, table.code)]);
export const memberships = pgTable("be_memberships", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id),
  issuer: text("issuer").notNull(), subject: text("subject").notNull(), name: text("name").notNull(), role: text("role").$type<JourneyRole>().notNull(),
  grants: jsonb("grants").$type<JourneyActor["grants"]>().notNull().default([]), resourceId: uuid("resource_id"), homeScope: text("home_scope"), active: boolean("active").notNull().default(true), revision: revision(), ...audit(),
}, table => [unique("be_memberships_identity_unique").on(table.issuer, table.subject), unique("be_memberships_org_id_unique").on(table.organizationId, table.id), index("be_memberships_resource_idx").on(table.organizationId, table.resourceId),
  uniqueIndex("be_memberships_active_resource_unique").on(table.organizationId, table.resourceId).where(sql`${table.active} and ${table.resourceId} is not null`),
  // Defined as DEFERRABLE INITIALLY DEFERRED in SQL to permit linking the first resource atomically.
  foreignKey({ name: "be_memberships_resource_fk", columns: [table.organizationId, table.resourceId], foreignColumns: [resourceOrganizationColumn(), resourceIdColumn()] }),
  foreignKey({ name: "be_memberships_home_fk", columns: [table.organizationId, table.homeScope], foreignColumns: [homes.organizationId, homes.code] }),
  check("be_memberships_role_check", sql`${table.role} in ('resource','placement_owner','home_leader','mission_owner','client_liaison','asset_access_owner','administrator')`),
]);
function resourceOrganizationColumn(): AnyPgColumn { return resources.organizationId; }
function resourceIdColumn(): AnyPgColumn { return resources.id; }
export const resources = pgTable("be_resources", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), name: text("name").notNull(), home: text("home").notNull(), ownerId: uuid("owner_id").notNull(), active: boolean("active").notNull().default(true), revision: revision(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), foreignKey({ columns: [table.organizationId, table.ownerId], foreignColumns: [memberships.organizationId, memberships.id] }), foreignKey({ name: "be_resources_home_fk", columns: [table.organizationId, table.home], foreignColumns: [homes.organizationId, homes.code] }), index("be_resources_owner_idx").on(table.organizationId, table.ownerId)]);
export const missions = pgTable("be_missions", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), name: text("name").notNull(), clientName: text("client_name").notNull(), clientId: uuid("client_id"), active: boolean("active").notNull().default(true), revision: revision(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), foreignKey({ name: "be_missions_client_fk", columns: [table.organizationId, table.clientId], foreignColumns: [clients.organizationId, clients.id] }), index("be_missions_client_idx").on(table.organizationId, table.clientId)]);
export const assignmentReferences = pgTable("be_assignment_references", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), resourceId: uuid("resource_id").notNull(), missionId: uuid("mission_id").notNull(), sourceReference: text("source_reference").notNull(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), unique().on(table.organizationId, table.resourceId, table.missionId, table.sourceReference), foreignKey({ columns: [table.organizationId, table.resourceId], foreignColumns: [resources.organizationId, resources.id] }), foreignKey({ columns: [table.organizationId, table.missionId], foreignColumns: [missions.organizationId, missions.id] })]);
export const templates = pgTable("be_templates", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), kind: text("kind").$type<JourneyKind>().notNull(), version: integer("version").notNull(), status: text("status").$type<JourneyTemplate["status"]>().notNull(), policyOwnerId: uuid("policy_owner_id"), body: jsonb("body").$type<JourneyTemplate>().notNull(), revision: revision(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), unique().on(table.organizationId, table.kind, table.version), foreignKey({ columns: [table.organizationId, table.policyOwnerId], foreignColumns: [memberships.organizationId, memberships.id] })]);
export const journeys = pgTable("be_journeys", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), resourceId: uuid("resource_id").notNull(), missionId: uuid("mission_id"), assignmentId: uuid("assignment_id"), ownerId: uuid("owner_id").notNull(), templateId: uuid("template_id").notNull(), kind: text("kind").$type<JourneyKind>().notNull(), revision: revision(), body: jsonb("body").$type<Omit<Journey, "obligations">>().notNull(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), foreignKey({ columns: [table.organizationId, table.resourceId], foreignColumns: [resources.organizationId, resources.id] }), foreignKey({ columns: [table.organizationId, table.missionId], foreignColumns: [missions.organizationId, missions.id] }), foreignKey({ columns: [table.organizationId, table.assignmentId], foreignColumns: [assignmentReferences.organizationId, assignmentReferences.id] }), foreignKey({ columns: [table.organizationId, table.ownerId], foreignColumns: [memberships.organizationId, memberships.id] }), foreignKey({ columns: [table.organizationId, table.templateId], foreignColumns: [templates.organizationId, templates.id] }), index("be_journeys_resource_idx").on(table.organizationId, table.resourceId, table.createdAt), index("be_journeys_mission_idx").on(table.organizationId, table.missionId, table.createdAt), index("be_journeys_owner_idx").on(table.organizationId, table.ownerId)]);
export const obligations = pgTable("be_obligations", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), journeyId: uuid("journey_id").notNull(), ownerId: uuid("owner_id").notNull(), fulfillerId: uuid("fulfiller_id").notNull(), verifierId: uuid("verifier_id").notNull(), instanceKey: text("instance_key").notNull(), revision: revision(), status: text("status").$type<ObligationStatus>().notNull(), body: jsonb("body").$type<BaggageObligation>().notNull(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), unique().on(table.organizationId, table.instanceKey), foreignKey({ columns: [table.organizationId, table.journeyId], foreignColumns: [journeys.organizationId, journeys.id] }), ...[table.ownerId, table.fulfillerId, table.verifierId].map(column => foreignKey({ columns: [table.organizationId, column], foreignColumns: [memberships.organizationId, memberships.id] })), index("be_obligations_journey_idx").on(table.organizationId, table.journeyId), index("be_obligations_owner_idx").on(table.organizationId, table.ownerId, table.status)]);
export const events = pgTable("be_events", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), actorId: uuid("actor_id").notNull(), journeyId: uuid("journey_id"), operation: text("operation").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), foreignKey({ columns: [table.organizationId, table.actorId], foreignColumns: [memberships.organizationId, memberships.id] }), foreignKey({ columns: [table.organizationId, table.journeyId], foreignColumns: [journeys.organizationId, journeys.id] }), index("be_events_journey_idx").on(table.organizationId, table.journeyId, table.occurredAt)]);
export const receipts = pgTable("be_receipts", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), actorId: uuid("actor_id").notNull(), idempotencyKey: uuid("idempotency_key").notNull(), requestHash: text("request_hash").notNull(), response: jsonb("response").notNull(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.actorId, table.idempotencyKey] }), foreignKey({ columns: [table.organizationId, table.actorId], foreignColumns: [memberships.organizationId, memberships.id] })]);
export const notices = pgTable("be_notices", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), id: uuid("id").notNull(), resourceId: uuid("resource_id").notNull(), journeyId: uuid("journey_id").notNull(), title: text("title").notNull(), body: text("body").notNull(), revision: revision(), publishedAt: timestamp("published_at", { withTimezone: true }).notNull().defaultNow(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.id] }), foreignKey({ columns: [table.organizationId, table.resourceId], foreignColumns: [resources.organizationId, resources.id] }), foreignKey({ columns: [table.organizationId, table.journeyId], foreignColumns: [journeys.organizationId, journeys.id] }), index("be_notices_resource_idx").on(table.organizationId, table.resourceId, table.publishedAt)]);
export const acknowledgments = pgTable("be_acknowledgments", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id), noticeId: uuid("notice_id").notNull(), actorId: uuid("actor_id").notNull(), noticeRevision: integer("notice_revision").notNull(), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }).notNull().defaultNow(), ...audit(),
}, table => [primaryKey({ columns: [table.organizationId, table.noticeId, table.actorId, table.noticeRevision] }), foreignKey({ columns: [table.organizationId, table.noticeId], foreignColumns: [notices.organizationId, notices.id] }), foreignKey({ columns: [table.organizationId, table.actorId], foreignColumns: [memberships.organizationId, memberships.id] })]);
